### ISSUE TITLE
Runtime error with callback function

### ISSUE THREAD

**Issue by dwater** [bastibe/PySoundCard#67]
I got following runtime errors when running anyone of the test scripts context_manager.py,  loopback_callback.py and playback_callback.py. 

> From cffi callback <function Stream.__init__.<locals>.callback_stub at 0x000001975AE45510>:
> Traceback (most recent call last):
>   File "D:\python\Anaconda3\lib\site-packages\pysoundcard.py", line 424, in callback_stub
>     time_info, status_flags)
>   File "context_manager.py", line 7, in callback
>     out_data[:] = in_data
> TypeError: 'int' object does not support item assignment

Here is the content of context_manager.py:

`from pysoundcard import Stream, continue_flag
import time

"""Loop back five seconds of audio data."""

def callback(in_data, out_data, time_info, status):
    out_data[:] = in_data
    return continue_flag

with Stream(samplerate=44100, blocksize=16, callback=callback):
    time.sleep(5)
`

**Comment by dwater** [comment]
I've checked the types of in_data, out_data, time_info, and status.
The results are as follows: 
<class 'numpy.ndarray'>
<class 'int'>
<class 'dict'>
<class 'int'>

**Comment by dwater** [comment]
I've changed the callback function. It works now. Thank you!

def callback(in_data, num_frames, time_info, status):
    return (in_data, continue_flag)
